SET SCHEMA PALTEST;
DROP TYPE PAL_BROWNSMOOTH_DATA_T;
CREATE TYPE PAL_BROWNSMOOTH_DATA_T AS TABLE("ID" INT, "RAWDATA" DOUBLE);
DROP TYPE PAL_BROWNSMOOTH_RESULT_T;
CREATE TYPE PAL_BROWNSMOOTH_RESULT_T AS TABLE("TIME" INT, "OUTPUT" DOUBLE);
DROP TYPE PAL_CONTROL_T;
CREATE TYPE PAL_CONTROL_T AS TABLE("NAME" VARCHAR(100), "INTARGS" INT,
"DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
DROP TYPE PAL_BROWNSMOOTH_STATISTIC_T;
CREATE TYPE PAL_BROWNSMOOTH_STATISTIC_T AS TABLE("NAME" VARCHAR(100), "VALUE"
DOUBLE);
DROP TABLE PAL_BROWNSMOOTH_PDATA_TBL;
CREATE COLUMN TABLE PAL_BROWNSMOOTH_PDATA_TBL("POSITION" INT, "SCHEMA_NAME"
NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO PAL_BROWNSMOOTH_PDATA_TBL VALUES (1,'PALTEST',
'PAL_BROWNSMOOTH_DATA_T','IN');
INSERT INTO PAL_BROWNSMOOTH_PDATA_TBL VALUES(2,'PALTEST', 'PAL_CONTROL_T','IN');
INSERT INTO PAL_BROWNSMOOTH_PDATA_TBL VALUES(3,'PALTEST',
'PAL_BROWNSMOOTH_RESULT_T','OUT');
INSERT INTO PAL_BROWNSMOOTH_PDATA_TBL VALUES(4,'PALTEST',
'PAL_BROWNSMOOTH_STATISTIC_T','OUT');
CALL SYS.AFLLANG_WRAPPER_PROCEDURE_DROP('PALTEST', 'BROWNSMOOTH_TEST_PROC');
CALL SYS.AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL', 'BROWNEXPSMOOTH', 'PALTEST',
'BROWNSMOOTH_TEST_PROC',PAL_BROWNSMOOTH_PDATA_TBL);
DROP TABLE PAL_BROWNSMOOTH_DATA_TBL;
CREATE COLUMN TABLE PAL_BROWNSMOOTH_DATA_TBL LIKE PAL_BROWNSMOOTH_DATA_T;
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (1,143.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (2,152.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (3,161.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (4,139.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (5,137.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (6,174.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (7,142.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (8,141.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (9,162.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (10,180.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (11,164.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (12,171.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (13,206.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (14,193.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (15,207.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (16,218.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (17,229.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (18,225.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (19,204.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (20,227.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (21,223.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (22,242.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (23,239.0);
INSERT INTO PAL_BROWNSMOOTH_DATA_TBL VALUES (24,266.0);
DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL ("NAME" VARCHAR(100),
"INTARGS" INT, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
INSERT INTO #PAL_CONTROL_TBL VALUES ('ALPHA', NULL,0.1, NULL);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DELTA',NULL, 0.2, NULL);
INSERT INTO #PAL_CONTROL_TBL VALUES ('FORECAST_NUM',72, NULL, NULL);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXPOST_FLAG',1, NULL, NULL);
INSERT INTO #PAL_CONTROL_TBL VALUES ('ADAPTIVE_METHOD',0, NULL, NULL);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MEASURE_NAME', NULL, NULL, 'MSE');
DROP TABLE PAL_BROWNSMOOTH_RESULT_TBL;
CREATE COLUMN TABLE PAL_BROWNSMOOTH_RESULT_TBL LIKE PAL_BROWNSMOOTH_RESULT_T ;
DROP TABLE PAL_BROWNSMOOTH_STATISTIC_TBL;
CREATE COLUMN TABLE PAL_BROWNSMOOTH_STATISTIC_TBL LIKE
PAL_BROWNSMOOTH_STATISTIC_T;
CALL PALTEST.BROWNSMOOTH_TEST_PROC(PAL_BROWNSMOOTH_DATA_TBL, "#PAL_CONTROL_TBL",
PAL_BROWNSMOOTH_RESULT_TBL, PAL_BROWNSMOOTH_STATISTIC_TBL)WITH OVERVIEW;
SELECT * FROM PAL_BROWNSMOOTH_RESULT_TBL;
SELECT * FROM PAL_BROWNSMOOTH_STATISTIC_TBL;
